[package]
name = 'whos'
description = 'whois library'
homepage = 'https://github.com/nc7s/whos'
repository = 'https://github.com/nc7s/whos.git'
authors = ['Blair Noctis <n@sail.ng>']
license = 'BSD-3-Clause'
version = '0.1.0'
edition = '2021'

exclude = ['md-whois/', '']

[dependencies]
lazy-regex = '3'
punycode = '0.4'
phf = { version = '0.11', features = ['macros'] }
thiserror = '1'

[build-dependencies]
ureq = '2.9'

[workspace]
members = ['build-data']
